project24_xfz/apps/cms/urls.py
from django.urls import path
from . import views
from . import courses_views
from . import staff_views

app_name = 'cms'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('qntoken/', views.qntoken, name='qntoken'),
    path('banners/', views.banners, name='banners'),
    path('add_banners/', views.add_banners, name='add_banners'),
    path('banner_list/', views.banner_list, name='banner_list'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
]

# 这是课程相关的url
urlpatterns += [
    path('pub_course/', courses_views.PubCourseView.as_view(), name='pub_course'),
]

# 员工管理相关
urlpatterns += [
    path('staffs/', staff_views.staffs_view, name='staffs'),
    path('add_staff/', staff_views.AddStaffView.as_view(), name='add_staff'),
]

project24_xfz/apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('list/', views.news_list, name='list'),
    path('public_comment/', views.public_comment, name='public_comment'),
]

project24_xfz/apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('cache/', views.cache_test, name='cache'),
    path('register/', views.register_view, name='register'),
]

project24_xfz/project24_xfz/urls.py
from apps.news import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    # path('search/', views.search, name='search'),
    path('search/', include('haystack.urls')),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path('course/', include('apps.course.urls')),
    path('payinfo/', include('apps.payinfo.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

project24_xfz/apps/cms/models.py
from django.db import models

project24_xfz/apps/course/models.py
from django.db import models
from shortuuidfield import ShortUUIDField


class CourseCategory(models.Model):
    name = models.CharField(max_length=100)


class Teacher(models.Model):
    username = models.CharField(max_length=100)
    avatar = models.URLField()
    position = models.CharField(max_length=100)
    profile = models.TextField()


class Course(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey('CourseCategory', on_delete=models.DO_NOTHING)
    teacher = models.ForeignKey('Teacher', on_delete=models.DO_NOTHING)
    video_url = models.URLField()
    cover_url = models.URLField()
    price = models.FloatField()
    profile = models.TextField()
    duration = models.IntegerField()
    pub_time = models.DateTimeField(auto_now_add=True)


class CourseOrder(models.Model):
    uid = ShortUUIDField(primary_key=True)
    course = models.ForeignKey('Course', on_delete=models.DO_NOTHING)
    buyer = models.ForeignKey('xfzauth.User', on_delete=models.DO_NOTHING)
    amount = models.FloatField(default=0)
    pub_time = models.DateTimeField(auto_now_add=True)
    # 1：代表支付宝支付 2：代表微信支付
    istype = models.SmallIntegerField(default=0)
    # 1：代表未支付，0：代表已支付
    status = models.SmallIntegerField(default=1)

project24_xfz/apps/news/models.py
from django.db import models


class NewsCategory(models.Model):
    name = models.CharField(max_length=20)


class News(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField()
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('NewsCategory', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey('xfzauth.User', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-pub_time']


class Comment(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey('News', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey('xfzauth.User', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-pub_time']


class Banners(models.Model):
    priority = models.IntegerField(default=0)
    image_url = models.URLField()
    link_to = models.URLField()
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-priority']

project24_xfz/apps/cms/forms.py
from django import forms
from apps.forms import FormMixin
from apps.news.models import News, Banners
from apps.course.models import Course


class EditNewsCategoryForm(forms.Form):
    pk = forms.IntegerField(error_messages={'Min_length': "pk值不能为空"})
    name = forms.CharField(max_length=20)


class WriteNewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['pub_time', 'category', 'author']


class EditNewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()
    pk = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['pub_time', 'category', 'author']


class AddBannersForm(forms.ModelForm, FormMixin):
    class Meta:
        model = Banners
        fields = ['priority', 'link_to', 'image_url']


class EditBannerForm(forms.ModelForm, FormMixin):
    pk = forms.IntegerField()

    class Meta:
        model = Banners
        fields = ['priority', 'link_to', 'image_url']


class PubCourseForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()
    teacher = forms.IntegerField()

    class Meta:
        model = Course
        exclude = ['category', 'teacher']

project24_xfz/apps/cms/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import View
from django.views.decorators.http import require_GET, require_POST
from apps.news.models import NewsCategory, News, Banners
from utils import restful
from .forms import EditNewsCategoryForm, WriteNewsForm, AddBannersForm, EditBannerForm, EditNewsForm
from django.conf import settings
import os
import qiniu
from apps.news.serializers import BannerSerializers
from django.core.paginator import Paginator
from django.utils.timezone import make_aware
from datetime import datetime
from urllib import parse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required


@staff_member_required(login_url='index')
def index(request):
    return render(request, 'cms/index.html')


@method_decorator(permission_required(perm='news.add_news', login_url='index'), name='dispatch')
class WriteNewsView(View):

    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories,
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            News.objects.create(title=title, desc=desc, thumbnail=thumbnail, content=content,
                                category=category, author=request.user)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


@require_GET
@permission_required(perm='news.add_news', login_url='index')
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'cms/news_category.html', context=context)


@require_POST
@permission_required(perm='news.add_news', login_url='index')
def add_news_category(request):
    name = request.POST.get('name')
    exists = NewsCategory.objects.filter(name=name).exists()
    if not exists:
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message="该分类已存在！")


@require_POST
@permission_required(perm='news.change_news', login_url='index')
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message="要修改的分类不存在！")

    else:
        return restful.params_error(message=form.get_error())


@require_POST
@permission_required(perm='news.delete_news', login_url='index')
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.unauth_error(message="删除的分类不存在！")


@require_POST
@staff_member_required(login_url='index')
def upload_file(request):
    file = request.FILES.get('file')
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    print(url)
    return restful.result(data={'url': url})


@require_GET
@staff_member_required(login_url='index')
def qntoken(request):
    access_key = settings.QINIU_ACCESS_KEY
    secret_key = settings.QINIU_SECRET_KEY

    bucket = settings.QINIU_DOMAIN
    q = qiniu.Auth(access_key, secret_key)
    token = q.upload_token(bucket)
    return restful.result(data={'token': token})


@permission_required(perm='banner.add_banner', login_url='index')
def banners(request):
    return render(request, 'cms/banners.html')


@permission_required(perm='banner.add_banner', login_url='index')
def banner_list(request):
    banner = Banners.objects.all()
    serializer = BannerSerializers(banner, many=True)
    return restful.result(data=serializer.data)


@permission_required(perm='banner.add_banner', login_url='index')
def add_banners(request):
    form = AddBannersForm(request.POST)
    if form.is_valid():
        priority = form.cleaned_data.get("priority")
        link_to = form.cleaned_data.get("link_to")
        image_url = form.cleaned_data.get("image_url")
        banner = Banners.objects.create(priority=priority, link_to=link_to, image_url=image_url)
        return restful.result(data={'banner_id': banner.pk})
    else:
        return restful.params_error(form.get_errors())


@permission_required(perm='banner.delete_banner', login_url='index')
def delete_banner(request):
    banner_id = request.POST.get('banner_id')
    Banners.objects.filter(pk=banner_id).delete()
    return restful.ok()


@permission_required(perm='banner.change_banner', login_url='index')
def edit_banner(request):
    form = EditBannerForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        priority = form.cleaned_data.get('priority')
        image_url = form.cleaned_data.get('image_url')
        link_to = form.cleaned_data.get('link_to')
        Banners.objects.filter(pk=pk).update(priority=priority, image_url=image_url, link_to=link_to)
        return restful.ok()
    else:
        return restful.params_error(form.get_errors())


@method_decorator(permission_required(perm='news.add_news', login_url='index'), name='dispatch')
class NewsListView(View):

    def get(self, request):
        page = int(request.GET.get('p', 1))
        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        # request.GET.get(参数，默认值)
        # 当没有传递参数时将使用默认值，
        # 但是当传递的参数为空时将不会使用默认值
        category_id = int(request.GET.get('category', 0))

        newses = News.objects.select_related('author', 'category').all()
        if start or end:
            if start:
                start_date = datetime.strptime(start, '%Y/%m/%d')
            else:
                start_date = datetime(year=2019, month=6, day=20)
            if end:
                end_date = datetime.strptime(end, '%Y/%m/%d')
            else:
                end_date = datetime.today()
            newses = newses.filter(pub_time__range=(make_aware(start_date), make_aware(end_date)))
        if title:
            newses = newses.filter(title__icontains=title)
        if category_id:
            newses = newses.filter(category=category_id)
        paginator = Paginator(newses, 2)
        page_obj = paginator.page(page)
        context_data = self.get_pagination_data(paginator, page_obj)
        context = {
            'start': start,
            'end': end,
            'title': title,
            'category_id': category_id,
            'url_query': '&'+parse.urlencode({
                'start': start or '',
                'end': end or '',
                'title': title or '',
                'category_id': category_id
            }),
            'categories': NewsCategory.objects.all(),
            'newses': page_obj.object_list,
            'paginator': paginator,
            'page_obj': page_obj
        }
        context.update(context_data)
        return render(request, 'cms/news_list.html', context=context)

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number
        num_pages = paginator.num_pages

        left_has_more = False
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page - around_count, current_page)

        if current_page >= num_pages - around_count - 1:
            right_pages = range(current_page + 1, num_pages + 1)
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_count + 1)

        return {
            # left_pages：代表的是当前这页的左边的页的页码
            'left_pages': left_pages,
            # right_pages：代表的是当前这页的右边的页的页码
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'num_pages': num_pages
        }


@method_decorator(permission_required(perm='news.change_news', login_url='index'), name='dispatch')
class EditNewsView(View):
    def get(self, request):
        news_id = int(request.GET.get('news_id'))
        context = {
            'news': News.objects.get(pk=news_id),
            'categories': NewsCategory.objects.all()
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = EditNewsForm(request.POST)
        if form.is_valid():
            category_id = form.cleaned_data.get('category')
            pk = form.cleaned_data.get('pk')
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category = NewsCategory.objects.get(pk=category_id)
            News.objects.filter(pk=pk).update(category=category, title=title,
                                              desc=desc, thumbnail=thumbnail, content=content)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


@require_POST

project24_xfz/front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}{% endblock %} | 小饭桌后台管理系统</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
  <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

<!-- jQuery 3 -->
<script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'adminlte/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/js/adminlte.min.js' %}"></script>
<script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'js/xfzajax.min.js' %}"></script>
<script src="{% static 'js/xfzalert.min.js' %}"></script>
<script src="{% static 'js/message.min.js' %}"></script>
{% block header %}

{% endblock %}

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  <header class="main-header">
    <a href="#" class="logo">
      <span class="logo-mini">CMS</span>
      <span class="logo-lg">小饭桌后台管理系统</span>
    </a>
    <nav class="navbar navbar-static-top">
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1561379870235&di=52e5ecd0a5251b0980af0da6835e7fe6&imgtype=0&src=http%3A%2F%2Fimg3.duitang.com%2Fuploads%2Fitem%2F201606%2F28%2F20160628141000_aXUmj.jpeg"
                   class="user-image" alt="User Image">
              <span class="hidden-xs">Robert Downey Jr.</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1561379870235&di=52e5ecd0a5251b0980af0da6835e7fe6&imgtype=0&src=http%3A%2F%2Fimg3.duitang.com%2Fuploads%2Fitem%2F201606%2F28%2F20160628141000_aXUmj.jpeg"
                     class="img-circle" alt="User Image">
                <p>
                  Python Web 开发工程师
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">个人中心</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">退出登陆</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <aside class="main-sidebar">
    <section class="sidebar">
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="查找">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <ul class="sidebar-menu" data-widget="tree">
          <li class="active">
              <a href="{% url 'cms:index' %}">
                  <i class="fa fa-home"></i>
                  <span>首页</span>
              </a>
          </li>
          {% if perms.news.change_news %}
              <li class="header">新闻管理</li>
              <li>
              <a href="{% url 'cms:news_list' %}">
                  <i class="fa fa-list"></i>
                  <span>新闻列表</span>
              </a>
          </li>
              <li>
                  <a href="{% url 'cms:write_news' %}">
                      <i class="fa fa-edit"></i>
                      <span>发布新闻</span>
                  </a>
              </li>
              <li>
                  <a href="{% url 'cms:news_category' %}">
                      <i class="fa fa-tag"></i>
                      <span>新闻分类</span>
                  </a>
              </li>
              <li>
                  <a href="{% url 'cms:banners' %}">
                  <i class="fa fa-window-restore"></i>
                  <span>轮播图</span>
                  </a>
              </li>
          {% endif %}
          {% if perms.course.change_course %}
              <li class="header">课程管理</li>
              <li>
              <a href="{% url 'cms:pub_course' %}">
                  <i class="fa fa-tv"></i>
                  发布课程
              </a>
              </li>
          {% endif %}
          {% if user.is_superuser %}
              <li class="header">员工管理</li>
              <li>
                  <a href="{% url 'cms:staffs' %}">
                      <i class="fa fa-group"></i>
                      员工管理
                  </a>
              </li>
          {% endif %}
      </ul>
    </section>
  </aside>
  <div class="content-wrapper">
    <section class="content-header">
        {% block content-header %}

        {% endblock %}
    </section>
    <section class="content">
        {% block content %}

        {% endblock %}
    </section>
  </div>
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>小饭桌</strong>后台管理系统
  </footer>

</div>

</body>
</html>

project24_xfz/front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}首页{% endblock %}

{% block header %}{% endblock %}

{% block content-header %}
    <h1>欢迎来到小饭桌CMS管理系统</h1>
{% endblock %}

project24_xfz/front/templates/cms/news_list.html
{% extends 'cms/base.html' %}
{% load news_filters %}

{% block title %}
    新闻列表管理
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/news_list.min.js' %}"></script>
    <style type="text/css">
    .margin-group{
        margin-right: 15px;
    }
    </style>
{% endblock %}

{% block content-header %}
<h1>新闻列表管理</h1>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-12">
    <div class="box">
        <div class="box-header">
            <form action="" class="form-inline">
                <div class="form-group margin-group">
                    <label for="">时间：</label>
                    {% if start %}
                        <input class="form-control" id="startpicker" type="text" name="start" placeholder="起始时间" readonly value="{{ start }}">
                    {% else %}
                        <input class="form-control" id="startpicker" type="text" name="start" placeholder="起始时间" readonly>
                    {% endif %}
                    <span>—</span>
                {% if end %}
                    <input class="form-control" id="endpicker" type="text" name="end" placeholder="结束时间" readonly value="{{ end }}">
                {% else %}
                    <input class="form-control" id="endpicker" type="text" name="end" placeholder="结束时间" readonly>
                {% endif %}
                </div>
                <div class="form-group margin-group">
                    <label for="">标题：</label>
                    {% if title %}
                        <input class="form-control" type="text" name="title" placeholder="关键字" value="{{ title }}">
                    {% else %}
                        <input class="form-control" type="text" name="title" placeholder="关键字">
                    {% endif %}
                </div>
                <div class="form-group margin-group">
                    <label for="">分类：</label>
                    <select class="form-control" name="category" id="category">
                        {% if category_id == 0 %}
                            <option value="0" selected>所有分类</option>
                        {% else %}
                            <option value="0">所有分类</option>
                        {% endif %}
                        {% for category in categories %}
                            {% if category_id == category.pk %}
                                <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                            {% else %}
                                <option value="{{ category.pk }}">{{ category.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group margin-group">
                    <button class="btn btn-primary">查询</button>
                </div>
                <div class="form-group">
                    <a href="{% url 'cms:news_list' %}">清除查询</a>
                </div>
            </form>
        </div>
        <div class="box-body">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>标题</th>
                    <th>分类</th>
                    <th>发布时间</th>
                    <th>作者</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for news in newses %}
                    <tr>
                    <th><a href="{% url 'news:news_detail' news_id=news.pk %}" target="_blank">{{ news.title }}</a></th>
                    <th>{{ news.category.name }}</th>
                    <th>{{ news.pub_time|time_format }}</th>
                    <th>{{ news.author.username }}</th>
                    <th>
                        <a href="{% url 'cms:edit_news' %}?news_id={{ news.pk }}" class="btn btn-info btn-xs">编辑</a>
                        <button class="btn btn-danger btn-xs delete-btn" data-news-id="{{ news.pk }}">删除</button>
                    </th>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="box-footer">
            <p class="pull-left">第{{ current_page }}/总共{{ num_pages }}页</p>
            <ul class="pagination pull-right">
                {#上一页#}
                {% if page_obj.has_previous %}
                    <li><a href="?p={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a></li>
                {% else %}
                    <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
                {% endif %}

                {# 是否需要出现三个点 #}
                {% if left_has_more %}
                    <li><a href="?p=1">1</a></li>
                    <li><a href="javascript:void(0);">...</a></li>
                {% endif %}

                {# 左边的页码 #}
                {% for left_page in left_pages %}
                    <li><a href="?p={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                {% endfor %}

                {# 当前的页面 #}
                <li class="active"><a href="?p={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                {# 右边的页码 #}
                {% for right_page in right_pages %}
                    <li><a href="?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                {% endfor %}

                {# 用来控制右边三个点 #}
                {% if right_has_more %}
                    <li><a href="javascript:void(0);">...</a></li>
                    <li><a href="?p={{ num_pages }}{{ url_query }}">{{ num_pages }}</a></li>
                {% endif %}

                {#下一页#}
                {% if page_obj.has_next %}
                    <li><a href="?p={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                {% else %}
                    <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
</div>
{% endblock %}